<style type="text/css">
	.navigation {
		max-width: none;
	}

	.home_banner {
		height: 600px;
	    overflow: hidden;
	    margin-top: -6%;
	}

	.owl-dots {
		position: relative;
		margin-top: -12% !important;
	}

	.banner-content {
		position: absolute;
	    padding-top: 20%;
	    right: 5%;
	    text-align: right;
	}

	.banner-content h1 {
		font-family: ProximaNova-Semibold,"Helvetica Neue",Verdana,Arial,sans-serif!important;
		color: #fff;
		font-weight: 400!important;
		margin-bottom: 15px;
	}

	.banner-content p {
		color: #fff;
	}

	.c-button {
	    min-width: 250px;
	    height: 45px;
	    padding: 0 45px;
	    border: 0;
	    border-radius: 0;
	    text-align: center;
	    -webkit-appearance: none;
	    font-size: 1em;
	    line-height: 48px;
	    opacity: 0.8;
	}

	.c-button:hover {
		opacity: 1;
		background: #fff;
	}

	.c-button:focus {
		opacity: 1;
		background: #fff;	
	}

	.c-button--white {
		background: #fff;
	    color: #1a1a1a;
	    -webkit-box-shadow: 0 0 1px 1px transparent;
	    -ms-box-shadow: 0 0 1px 1px transparent;
	    -o-box-shadow: 0 0 1px 1px transparent;
	    box-shadow: 0 0 1px 1px transparent;
	}

	.block-title strong {
		margin-left: 45%;
	}

	.block-content {
		padding: 0 2%;
	}
</style>
<div class="home_banner">
	<div class="owl-carousel owl-theme">
		<div class="item">
			<div class="banner-content">
				<h1>MASTERMIND WORLD</h1>
				<p>SCENE.2 AMBITION.</p>
				<button class="c-button c-button--white">Online Now</button>
			</div>
			<img src="http://192.168.2.104/m2design/pub/media/banner_1.jpg"  alt="1" >
		</div>
		<div class="item"><img src="http://192.168.2.104/m2design/pub/media/banner_2.jpg" alt="2" ></div>
		<div class="item"><img src="http://192.168.2.104/m2design/pub/media/banner_3.jpg" alt="3" ></div>
	</div>
</div>

<input type="hidden" id="test" value="one">